BlankMovieCoreApplication/MovieApp.UI/Controllers/TheaterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using MovieAPP.Entity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.UI.Controllers
{
    public class TheaterController : Controller
    {
        IConfiguration _configuration;
        
        public TheaterController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> ShowTheaterDetails()
        {
            using (HttpClient client = new HttpClient())
            {
                //  server api=http://localhost:5000/api/Theater/SelectTheater

                string endPoint = _configuration["WebApibaseUrl"] + "Theater/SelectTheater";

                // we are passing getrequest to server  with urel
                using (var response = await client.GetAsync(endPoint))
                {
                    if(response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        //string-json results come
                        var result = await response.Content.ReadAsStringAsync();
                        //deseralize json-string to object i.e UserModel
                        var theaterModel = JsonConvert.DeserializeObject<List<TheaterModel>>(result);
                      
                        return View(theaterModel);
                    }
                }

                return View();
            }
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(TheaterModel theaterModel)
        {
            // ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theaterModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApibaseUrl"] + "Theater/Register";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Registered";
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "WrongEntry";
                    }
                }
            }
            return View();
        }


        public async Task<IActionResult> EditTheater(int theaterId)
        {

            using (HttpClient client = new HttpClient())

            {
                //server api=http://localhost:5000/api/Theater/SelectTheaterById
                string endPoint = _configuration["WebApibaseUrl"] + "Theater/SelectTheaterById?theaterId=" + theaterId;
                // we are passing getrequest to server  with urel
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)

                    {
                        //string-json results come
                        var result = await response.Content.ReadAsStringAsync();

                        //deseralize json-string to object i.e UserModel
                        var theaterModel = JsonConvert.DeserializeObject<TheaterModel>(result);
                        return View(theaterModel);
                    }




                }


            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditTheater(TheaterModel theaterModel)
        {
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(theaterModel), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApibaseUrl"] + "Theater/UpdateTheater";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = "Theater Updated SuccessFully !!";
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "WrongEntry";
                    }
                }
            }
            return View();

        }


        [HttpGet]
        public async Task<IActionResult> Delete(int theaterId)
        {

            using (HttpClient client = new HttpClient())

            {
                //server api=http://localhost:5000/api/Theater/SelectTheaterById
                string endPoint = _configuration["WebApibaseUrl"] + "Theater/SelectTheaterById?theaterId=" + theaterId;
                // we are passing getrequest to server  with urel
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)

                    {
                        //string-json results come
                        var result = await response.Content.ReadAsStringAsync();

                        //deseralize json-string to object i.e UserModel
                        var theaterModel = JsonConvert.DeserializeObject<TheaterModel>(result);
                        return View(theaterModel);
                    }




                }


            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(TheaterModel theaterModel)
        {
            using (HttpClient client = new HttpClient())
            {

                string endPoint = _configuration["WebApibaseUrl"] + "Theater/DeleteTheater?theaterId=" + theaterModel.TheaterId;
                using (var response = await client.DeleteAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Success";
                        ViewBag.message = " Theater Deleted SuccessFully !!";
                    }

                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "WrongEntry";
                    }
                }
            }
            return View();

        }



    }
}

BlankMovieCoreApplication/MovieApp.UI/Views/Theater/Delete.cshtml
@model MovieAPP.Entity.TheaterModel

@{
    ViewData["Title"] = "Delete";
}


<a asp-action="ShowTheaterDetails" asp-controller="Theater">Theater Details</a>
<h1>Delete</h1>

<form method="post">

    <div class="form-group">
        <label>TheaterId</label>
        <input type="text" class="form-control" Asp-for="TheaterId" />
    </div>
    <div class="form-group">
        <label>TheaterName</label>
        <input type="text" class="form-control" Asp-for="TheaterName" />
    </div>

    <div class="form-group">
        <label>TheaterLocation</label>
        <input type="text" class="form-control" Asp-for="TheaterLocation" />
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control" Asp-for="Email" />
    </div>



    <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control" Asp-for="Password" />
    </div>


  



    <input type="submit" value="Delete" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-secondary" />
</form>
@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

BlankMovieCoreApplication/MovieApp.UI/Views/Theater/EditTheater.cshtml
@model MovieAPP.Entity.TheaterModel

@{
    ViewData["Title"] = "EditTheater";
}


<a asp-action="ShowTheaterDetails" asp-controller="Theater">Theater Details</a>
<h1>EditTheater</h1>

<form method="post">
    <div class="form-group">
        <label>TheaterName</label>
        <input type="text" class="form-control" Asp-for="TheaterName" />
    </div>

    <div class="form-group">
        <label>TheaterLocation</label>
        <input type="text" class="form-control" Asp-for="TheaterLocation" />
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control" Asp-for="Email" />
    </div>



    <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control" Asp-for="Password" />
    </div>





    <input type="submit" value="Update" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-secondary" />
</form>
@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

BlankMovieCoreApplication/MovieApp.UI/Views/Theater/Register.cshtml
@model MovieAPP.Entity.TheaterModel



@{
    ViewData["Title"] = "Register";
}

<a asp-action="ShowTheaterDetails" asp-controller="Theater">Theater Details</a>

<h1>Register</h1>

<form method="post">
    
    <div class="form-group">
        <label>TheaterName</label>
        <input type="text" class="form-control" placeholder="TheaterName" Asp-for="TheaterName" />
    </div>

    <div class="form-group">
        <label>TheaterLocation</label>
        <input type="text" class="form-control" placeholder="TheaterLocation"Asp-for="TheaterLocation" />
    </div>



    <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control" placeholder="Email" Asp-for="Email" />
    </div>


    <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control"  placeholder="Password"Asp-for="Password" />
    </div>



    <input type="submit" value="Register" class="btn btn-primary" />
    <input type="button" value="Reset" class="btn btn-secondary" />
</form>
@if (ViewBag.status == "Success")
{
    <div class="alert alert-success">@ViewBag.message</div>
}
else if (ViewBag.status == "Error")
{
    <div class="alert alert-danger">@ViewBag.message</div>
}

BlankMovieCoreApplication/MovieApp.UI/Views/Theater/ShowTheaterDetails.cshtml
@model IEnumerable<MovieAPP.Entity.TheaterModel>

@{
    ViewData["Title"] = "ShowTheaterDetails";
}

<h1>ShowTheaterDetails</h1>



<table class="table table-bordered  table-dark">
    <thead>
        <tr>
            <th>TheaterId</th>
            <th>TheaterName</th>
            <th>TheaterLocation</th>
            <th>Email</th>
            <th>Password</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.TheaterId</td>
                <td>@item.TheaterName</td>
                <td>@item.TheaterLocation</td>
                <td>@item.Email</td>
                <td>@item.Password</td>
                <td><a asp-action="EditTheater" asp-controller="Theater" asp-route-TheaterId="@item.TheaterId">Edit</a></td>
                <td><a asp-action="Delete" asp-controller="Theater" asp-route-TheaterId="@item.TheaterId">Delete</a></td>
            </tr>
        }
    </tbody>
</table>